### ISSUE TITLE
annotate_contigs fails in run_test

### ISSUE THREAD

**Issue by pratarora** [Oshlack/MINTIE#10]
Hi!

Thank you for your preprint. I was trying to test the pipeline but faced the following issue. Could you help?

============================== Stage annotate_contigs (allvars-case) ===============================
Traceback (most recent call last):
  File "/home/usr/data/mintie/MINTIE-v0.3.5/annotate/annotate_contigs.py", line 720, in <module>
    main()
  File "/home/usr/data/mintie/MINTIE-v0.3.5/annotate/annotate_contigs.py", line 717, in main
    annotate_contigs(args)
  File "/home/usr/data/mintie/MINTIE-v0.3.5/annotate/annotate_contigs.py", line 659, in annotate_contigs
    bam = pysam.AlignmentFile(args.bam_file, 'rc')
  File "pysam/libcalignmentfile.pyx", line 742, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 991, in pysam.libcalignmentfile.AlignmentFile._open
ValueError: file has no sequences defined (mode='rc') - is it SAM/BAM format? Consider opening with check_sq=False
Cleaned up file allvars-case/annotated_contigs.vcf to .bpipe/trash/annotated_contigs.vcf.3
Cleaned up file allvars-case/annotated_contigs_info.tsv to .bpipe/trash/annotated_contigs_info.tsv.3
ERROR: stage annotate_contigs failed: Command in stage annotate_contigs failed with exit status = 1 : 

/home/usr/miniconda3/envs/mintie/bin/python /home/usr/data/mintie/MINTIE-v0.3.5/annotate/annotate_contigs.py             allvars-case allvars-case/aligned_contigs_against_genome.bam             /home/usr/data/mintie/MINTIE-v0.3.5/ref/chess2.2.info /home/usr/data/mintie/MINTIE-v0.3.5/ref/chess2.2.gtf             allvars-case/annotated_contigs.bam allvars-case/annotated_contigs_info.tsv             --minClip 20             --minGap 7             --minMatch 30,0.3             --log /home/usr/data/mintie/MINTIE-v0.3.5/allvars-case/annotate.log > allvars-case/annotated_contigs.vcf

**Comment by mcmero** [comment]
This looks like the GMAP alignment against the genome step failed. Please check your installation of GMAP (have a look at your `tools.groovy` file and check that the `gmap=` entry has a valid path to the GMAP binary). You can also have a look at your `commandlog.txt` file and try running the gmap step manually to check for any errors.
