### ISSUE TITLE
Guidance around key parameters

### ISSUE THREAD

**Issue by h-joshi** [Oshlack/MINTIE#12]
It would be great to get some guidance around impact of these parameters. It's not immediately clear how increasing or decreasing these parameters affects sensitivity.

```
-p Ks=79,49 comma-separated kmer lengths for de novo assembly. This option affects SOAPdenovotrans and rnaSPAdes (but not Trinity). Please ensure that your read length is longer than ALL kmer lengths specified.
-p min_read_length=50 minimum read length for trimming. NOTE: Please ensure this is greater than your minimum Kmer length.
-p min_contig_len=100 minimum length required for for assembled contig to be kept.
```

**Comment by mcmero** [comment]
You are right, these parameters are a little tricky to set correctly. I've added an answer to this question in the wiki [FAQ](https://github.com/Oshlack/MINTIE/wiki/FAQ#how-do-the-config-parameters-k-mer-ks-minimum-read-length-min_read_length-and-minimum-contig-length-min_contig_len-influence-sensitivity).

**Comment by h-joshi** [comment]
Thanks that really helped
