### ISSUE TITLE
Question about interpretation of cpos

### ISSUE THREAD

**Issue by raerose01** [Oshlack/MINTIE#14]
Hello, and thanks for creating such a useful tool. I had a question about understanding the "cpos" output, particularly when the alignment includes gaps. For instance, I have the following result:

chr1 | pos1 | strand1 | chr2 | pos2 | strand2 | variant_type | overlapping_genes | variant_id | partner_id | vars_in_contig | VAF | varsize | contig_varsize | cpos | contig_len | contig_cigar
--- | --- | --- | --- |  --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | ---
chr1 | 973327 | - | chr1 | 973499 | - | RI | PLEKHN1 | k49_231483a | . | 1 | 0.5953358 | 173 | 173 | 141 | 695 |  48M137N137M436N150M175N360M

The retained intron position in question here is between the two rightmost exons in the attached screenshot from IGV.

<img width="1498" alt="Screen Shot 2021-08-23 at 2 20 05 PM" src="https://user-images.githubusercontent.com/7635833/130463592-92f55c0e-d059-46ef-839c-e648eec864db.png">

However, if I were to annotate that cpos myself, I'd say it was at 477 (specifically it looks like the RI is from 477 - 477+173). I'm not sure I see how 141 is calculated.

Thanks for the help, 

Rachel

**Comment by mcmero** [comment]
Thank you for raising this. The transcript in the screenshot is aligned on the antisense strand, which would mean that the cpos will be calculated from the right-hand side of the transcript. Even so, the cpos doesn't look right, so this is likely a bug. I will have to investigate further. If you could send me the transcript sequence of the assembled contig, that would be helpful.

**Comment by raerose01** [comment]
Sure, thanks.

Transcript sequence for k49_231483 is: 

TCAACCTGGAGGAGAAGGAGAAGCAGATCCGCTCCTTCCTGATTGAAGGCCCCCTCATCAACACCATCCGCGTGGTGTGCGCCAGCTACGAGGACTACGGTCACTGGCTGCTGTGCCTTCGCGCTGTCACCCACAGGGAGGGGGCCCCGCCGCTGCCTGGTGCCGAGAGCTTCCCAGGGTCGCAGGTTATGGGCAGTGGCCGAGGCTCACTCTCCTCAGGCGGACAGACCAGCTGGGACTCGGGGTGCTTGGCGCCCCCCTCCACCCGCACCAGCCACTCCCTGCCTGAGTCCTCAGTGCCATCCACCGTGGGCTGCTCCTCCCAGCACACACCGGACCAGGCCAACTCTGACCGTGCCAGCATTGGCCGACGGAGGACCGAGCTGAGACGCAGTGGCAGCAGCCGGTCACCCGGGAGCAAGGCCCGGGCAGAGGGCCGCGGCCCTGTCACCCCACTGCACCTGGACCTGACCCAGGTGGGCCCAGCACACCCACACAGCCCCTGGCCTGGTTCCCACCGTTCCGCACCACTGGTCTCTGTCTCTGGGCCCAGTTGTCCTGGAGCCACCCAGAGGCCTCTTGCACAGAGAAGGGGTGGCCTAGGCTGTTTCTAGCCGAGAAGCCCATTTCTCCCACCTCTGCCCTGCAGCTGCACAGGCTGAGCCTGGAGAGCAGCCCAGATGCCCCTGACCACA

In case it's helpful, the seq info from the TSV output is:
seq_loc1 | seq_loc2 | seq1 | seq2
------- | ------- | ------- | ------- 
k49_231483:121-161 | k49_231483:294-334 | CTCTGGGTGGCTCCAGGACAACTGGGCCCAGAGACAGAGA | GCTGCCACTGCGTCTCAGCTCGGTCCTCCGTCGGCCAATG

**Comment by mcmero** [comment]
It looks like these results were generated using an older version of MINTIE. Please update to the latest version, which should give the correct cpos.
