### ISSUE TITLE
Running MINTIE with Single end dataset

### ISSUE THREAD

**Issue by aswathyseb** [Oshlack/MINTIE#16]
Hi,

My rnaseq dataset is single end and I want to run MINTIE with it. I get the error that

`stage fastq_dedupe failed: Insufficient inputs: at least 2 inputs are expected with extension .gz but only 1 are available`

**How can I run MINTIE with single end dataset?**

Inoder to test, I tried to run the test dataset after deleting R2 files from cases and controls as

`mintie -w -p test_params.txt cases/*.fastq.gz controls/*.fastq.gz`

in the test_params.txt, I made the following changes

`-p fastqCaseFormat=cases/%_R1.fastq.gz`
  `-p fastqControlFormat=controls/%_R1.fastq.gz`

I get the same error. Could you let me know how to run the tool on single end dataset?

Thanks,

**Comment by mcmero** [comment]
MINTIE doesn't officially support single-end reads. However, I did have an old branch with single-end support. I've taken this alternate pipeline and integrated it into the the main branch. 

As this is not on bioconda yet, install as follows: run `export $MINTIEDIR=<path>` where the path is the same one shown when running `mintie -h`. Then:

```
git clone https://github.com/Oshlack/MINTIE.git && cd MINTIE
cp $MINTIEDIR/references.groovy .
```

Now activate your mintie environment for the dependencies, and run the pipeline as follows:

```
bpipe run -@params.txt MINTIE_SE.groovy cases/*.fastq.gz controls/*fastq.gz
```
