### ISSUE TITLE
Cluster Setup using conda environments

### ISSUE THREAD

**Issue by scuttlebud** [Oshlack/MINTIE#18]
Hello,

You state in your Documentation that Mintie needs to be installed using the conda base environment if used on a cluster. On our cluster this is a bit tricky since there are conflicting packages and in general users may want to use environments to avoid conflicts with other packages they use. 
Is there a way one could propagate environments? Is this limitation due to the generation of the submission scripts through bpipe? I'm not familiar with bpipe, but from a first glance it looked as if there is not an option yet to easily extend the submission scripts. 

Thank you

**Comment by mcmero** [comment]
As you describe, this is currently tricky as bpipe doesn't currently have support for conda, or for easily editing the submission scripts (prior to executing the step). This functionality may be added in the future, but for now, the only workaround might be a bit of a hack of the submission script.

First find the submission scripts by loading your environment and running `which bpipe`. It will look something like this: `.conda/envs/mintie/bin/bpipe`, which is just a symlink, the real directory will look like: `~/.conda/envs/mintie/opt/bpipe-0.9.11/bin/`. This will contain the submission scripts that can be modified. E.g. if you are using slurm, modify this line to load your conda environment: [bpipe-slurm.sh#L230](https://github.com/ssadedin/bpipe/blob/master/bin/bpipe-slurm.sh#L230). It's not ideal, but hope it helps.
