### ISSUE TITLE
can't manally construct reference for hg19

### ISSUE THREAD

**Issue by KeqiangYan** [Oshlack/MINTIE#25]
Hi, I tried to running this with hg19. However, the CHESS database not support to this version. Can you give me some suggestions of how to construct hg19 reference for this tool?

Thanks

**Comment by mcmero** [comment]
CHESS isn't required but you'll have to build your reference file manually. Please [see here for more details](https://github.com/Oshlack/MINTIE/wiki/Install#references). Note that splice motif checking won't work on references other than hg38, so make sure you set `splice_motif_mismatch=4`.
