### ISSUE TITLE
Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7

### ISSUE THREAD

**Issue by deb0612** [Oshlack/MINTIE#26]
Dear sir I tried to install mintie with conda and manually. However both of them show the error:
"java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7"
![image](https://user-images.githubusercontent.com/29038270/210059128-adcbdcc8-f8cc-4348-8cb8-870d6b823c47.png)
Should I need to reset my java?

**Comment by mcmero** [comment]
Thanks for raising. It looks like newer versions of bpipe don't play nicely with MINTIE. 

I'll work on locking down MINTIE's bpipe version in bioconda.

In the meantime, you can fix this by installing an older version of bpipe (make sure you have your mintie env loaded):
```bash
conda install -c conda-forge -c bioconda bpipe=0.9.9.2
```

**Comment by ssadedin** [comment]
@deb0612 it looks like you might be using a version of java newer than JDK11. I think you might run into trouble even using older versions of Bpipe with that. Could you see if you can install JDK8 (java 1.8) and see if it works with that?

I am currently working to release an "official" version of Bpipe that is fully tested for later versions of Java but it may still be  a little bit before it's ready.

**Comment by mcmero** [comment]
Fixed by https://github.com/bioconda/bioconda-recipes/pull/38762.
