### ISSUE TITLE
Pipeline failed at Assemble stage

### ISSUE THREAD

**Issue by DrShamy** [Oshlack/MINTIE#29]
Dear Marek,

I have installed Mintie using Mamba on WSL (Ubuntu). Although I managed to install the reference genome (mintie -r), I'm facing an error at the Assemble stage at the test datasets run (after mintie -t). The Trimming stage seems to be working correctly (I got trimmed output files), but the pipeline fails to create "denovo_filt.fasta" and/or "SOAP.fasta" files properly (those files are missing). I also tried to install Mintie manually, including all required packages from the pipeline (added references to the "tool.groovy" file), including Trinity and rnaSPAdes packages. However, I faced exactly the same problem. Do you maybe have an idea of what and where might be the problem causing this error? Should I maybe have to reconfigure SOAPdenovo-Trans parameters somehow? I have ran and tested all packages in the pipeline individually and they are all working correctly. So, I have no other option but to ask you to help me in solving this problem as I'm very keen to use Mintie in my project (might be exactly what I need).
Thank you in advance.

![SOAP error](https://user-images.githubusercontent.com/125593597/220458866-596a17a5-c7ad-4c5f-8f06-0ecbc8e10a59.png)

**Comment by nadiadavidson** [comment]
Hi DrShamy, 

The assembly stage tends to use quite a lot of computational resources (up to and exceeding 100 GB of RAM). Could it be that you've hit the memory limit?

Cheers,
Nadia.

**Comment by DrShamy** [comment]
Hi Nadia,

Thank you very much for the reply. I have 32GB of RAM memory available on the WSL, while used memory has never exceeded 20GB. And I'm trying to run Mintie on the test data (generated by "mintie -t" command), which contains only ~423K reads as far as I can see. Besides, the algorithm crashes as soon as it reaches Assemble stage which suggests it failed to start doing the actual assembly.  So it's unlikely that the issue was caused by reaching the top of my memory capacity.

**Comment by mcmero** [comment]
Can you check to make sure you're running v1.03 of SOAPdenovo-Trans: `SOAPdenovo-Trans-127mer --version`?

You also say you get the same issue with Trinity and rnaSPAdes; did you make sure to change the assembler in the `params.txt` file?
