### ISSUE TITLE
Stage post-process fail

### ISSUE THREAD

**Issue by cmayoh** [Oshlack/MINTIE#3]
Hi Marek,
I've updated the MINTIE code to the latest that is on github as of yesterday (18 May 2020) and now I get the following error within the stage post-process:
==================================== Stage post_process (Rh18) =====================================
/usr/local/lib/python3.7/site-packages/pandas/compat/__init__.py:84: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/usr/local/MINTIE/annotate/post_process.py", line 180, in <module>
    main()
  File "/usr/local/MINTIE/annotate/post_process.py", line 167, in main
    contigs = add_de_info(contigs, de_results)
  File "/usr/local/MINTIE/annotate/post_process.py", line 92, in add_de_info
    contigs = contigs.drop_duplicates(ignore_index=True)
TypeError: drop_duplicates() got an unexpected keyword argument 'ignore_index'
Cleaned up file Rh18/Rh18_results.tsv to .bpipe/trash/Rh18_results.tsv.1
ERROR: stage post_process failed: Command in stage post_process failed with exit status = 1 :

/usr/local/bin/python3.7 /usr/local/MINTIE/annotate/post_process.py             Rh18             Rh18/novel_contigs_info.tsv             Rh18/eq_classes_de.txt             Rh18/vaf_estimates.txt                                       --log /data/SarcomaCellLines/Analysis/Rh18/MINTIE/Rh18/postprocess.log > Rh18/Rh18_results.tsv

These are the parameters I'm using:
" -p threads=8 -p genome_mem=8000000000 -p assembly_mem=8 -p assembler=soap -p scores=33 -p min_read_length=50 -p max_read_length=150 -p minQScore=20 -p Ks=79,49 -p min_gap=7 -p min_clip=20 -p min_match=30,0.3 -p min_logfc=2 -p min_cpm=0.1 -p fdr=0.05 -p sort_ram=4G -p gene_filter= -p var_filter= -p assemblyFasta=  -p test_mode=false -p fastqCaseFormat=cases/%_R*.fastq.gz -p fastqControlFormat=controls/%_R*.fastq.gz"

Thank you!

**Comment by cmayoh** [comment]
Note: I realised my update of panda failed so I was using version 0.25 when version >1.0 was needed. Therefore successfully updated pandas and the error resolved and ran to completion

**Comment by mcmero** [comment]
Thank you for raising this. Updating to pandas >v1.0 fixes the issue, but we do want MINTIE to be backwards compatible with older versions of pandas. As this flag is not essential, I have removed it in the latest commit.
