### ISSUE TITLE
Running MINTIE without control and without bpipe

### ISSUE THREAD

**Issue by yasin-uzun** [Oshlack/MINTIE#30]
Hi,

It is mentioned in the documentation that MINTIE can be run without control data as follows:

`bpipe run @$MINTIEDIR/params.txt $MINTIEDIR/MINTIE.groovy $cases`

Can MINTIE be run without control data and without bpipe like this?:

`mintie -w -p params.txt cases/*.fastq.gz `

**Comment by mcmero** [comment]
Yes, the two are equivalent. Note that you will might get an error on some earlier versions of bpipe when running with no controls. If using the bioconda version, you can update to latest bioconda version of bpipe using:

```
mamba install -c conda-forge -c bioconda bpipe=0.9.11 opendjk=11
```

**Comment by yasin-uzun** [comment]
Thanks so much for the guidance.
