### ISSUE TITLE
The pattern provided did not match

### ISSUE THREAD

**Issue by npatel-ah** [Oshlack/MINTIE#32]
Hello, 
I am trying to use Mintie (v4.2-0) for mouse reference ( I managed to create the groovy file) , however, I am keep getting below error. My pattern seems correct.    Please let me know if I am missing anything here, could it be because I have "-" in my sample ids, if so is there a way to get around that  ? 

`ERROR: The pattern provided 'cases/%_R*.fastq.gz' did not match any of the files provided as input [cases/SampleXR-01-04_R1.fastq.gz, cases/SampleXR-01-04_R2.fastq.gz, cases/SampleXR-01-05_R1.fastq.gz, cases/SampleXR-01-05_R2.fastq.gz, cases/SampleXR-01-06_R1.fastq.gz, cases/SampleXR-01-06_R2.fastq.gz, controls/SampleXR-01-01_R1.fastq.gz, controls/SampleXR-01-01_R2.fastq.gz, controls/SampleXR-01-02_R1.fastq.gz, controls/SampleXR-01-02_R2.fastq.gz, controls/SampleXR-01-03_R1.fastq.gz, controls/SampleXR-01-03_R2.fastq.gz]
`

Here is my param.txt
```

-p threads=16
-p assembly_mem=200
-p assembler=soap
-p scores=33
-p min_read_length=80
-p min_contig_len=100
-p minQScore=20
-p Ks=79,49
-p min_gap=7
-p min_clip=20
-p min_match=30,0.3
-p min_logfc=5
-p min_cpm=0.1
-p fdr=0.05
-p sort_ram=4G
-p gene_filter=
-p var_filter=
-p splice_motif_mismatch=4
-p fastqCaseFormat=cases/%_R*.fastq.gz
-p fastqControlFormat=controls/%_R*.fastq.gz
-p assemblyFasta=
-p run_de_step=true

```
Also, is there an option to provide custom reference.groovy, beside replacing it in $MINTIEDIR ?

**Comment by mcmero** [comment]
Currently there's no way to provide a custom reference.groovy file unfortunately. 

Regarding the error, can you please post your whole run command and which version of bpipe you are running? A `tree` of your run directory may also be useful.

**Comment by npatel-ah** [comment]
Hey, Thank you for your reply. 

Here my command

`mintie -w -p params.txt cases/*.fastq.gz controls/*.fastq.gz`

here is the tree
```

├── cases
│   ├── SampleXR-04_R1.fastq.gz
│   ├── SampleXR-04_R2.fastq.gz
│   ├── SampleXR-05_R1.fastq.gz
│   ├── SampleXR-05_R2.fastq.gz
│   ├── SampleXR-06_R1.fastq.gz
│   └── SampleXR-06_R2.fastq.gz
├── controls
│   ├── SampleXR-01_R1.fastq.gz
│   ├── SampleXR-01_R2.fastq.gz
│   ├── SampleXR-02_R1.fastq.gz
│   ├── SampleXR-02_R2.fastq.gz
│   ├── SampleXR-03_R1.fastq.gz
│   └── SampleXR-03_R2.fastq.gz
├── params.txt
└── references_mm10.groovy
└── util -> $HOME/miniconda3/envs/mamba/envs/mintie/share/mintie-0.4.2-0/util


```


The "references_mm10.groovy" is copied to share directory 

```
find $HOME/miniconda3/envs/mamba/envs/mintie/share -name "*groovy"
$HOME/miniconda3/envs/mamba/envs/mintie/share/mintie-0.4.2-0/MINTIE.groovy
$HOME/miniconda3/envs/mamba/envs/mintie/share/mintie-0.4.2-0/MINTIE_SE.groovy
$HOME/miniconda3/envs/mamba/envs/mintie/share/mintie-0.4.2-0/tools.groovy
$HOME/miniconda3/envs/mamba/envs/mintie/share/mintie-0.4.2-0/references.groovy

Thanks,

```

**Comment by mcmero** [comment]
I can't seem to replicate this bug using your input file names.

Can you try installing bpipe with JDK 11?

```
conda activate mintie
conda install -c conda-forge -c bioconda openjdk=11 bpipe -y
```

**Comment by npatel-ah** [comment]
That did the job, thanks a lot for quick response.
