### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by luxinyi197** [Oshlack/MINTIE#35]
HI
I installed MINTIE using suggested method(using mamba). The installation was completed without issue and also successfully dowloaded the reference files. I tried to run MINITE on the test data, it was also successfully finished. However I was running MINTIE on my real data, I can only run 1 case vs 1 controls just like the test data. When I wanted to try to running MINTIE with 3 controls, I always prompt no space left on device. 
``============================= Found 1 failed commands from run 925835 ==============================`

`==================================== Command fastq_dedupe (374) ====================================`

```
Command    : gunzip -c cases/allvars-case_R1.fastq.gz > allvars-case/temp1.fastq ; gunzip -c cases/allvars-case_R2.fastq.gz > allvars-case/temp2.fastq ; echo allvars-case/temp1.fastq > allva echo allvars-case/temp2.fastq >> allvars-case/fastq.list ;             echo "Reads before:" ; wc -l allvars-case/temp1.fastq ;             fastuniq -i allvars-case/fastq.list -o allvars-castq -p allvars-case/allvars-case.2.fastq ;             echo "Reads after:" ; wc -l allvars-case/allvars-case.1.fastq ;             gzip allvars-case/allvars-case.1.fastq allvars-case/allvars-       rm allvars-case/fastq.list allvars-case/temp1.fastq allvars-case/temp2.fastq
Started    : Mon Jun 26 08:30:38 CST 2023
Stopped    : Mon Jun 26 08:59:01 CST 2023
Exit Code  : 1
```
```
Config: 
                   Name           |    Value    
          --------------------------------------
          procs                   | 1           
          memory                  | 160         
          max_per_command_threads | 16          
          executor                | local       
          mem_param               | mem         
          name                    | fastq_dedupe
          proc_mode               | 1           
          usePollerFileWatcher    | true        
          walltime                | 20:00:00    
          queue                   | batch       
          concurrency             | 16       
```   

Output    : 

	Reads before:
	209526696 allvars-case/temp1.fastq
	Reads after:
	138463916 allvars-case/allvars-case.1.fastq
	
	gzip: allvars-case/allvars-case.1.fastq.gz: No space left on device
`
If you have any suggestions for how I can troubleshoot this, that would be great.
Also I want to know how much space is required to run MINTIE.
Thanks

**Comment by mcmero** [comment]
I would check how much space you have on the file system where your run directory is. The test data is quite small, however, the references that MINTIE uses are ~17GB (the whole conda environment including references is around 19GB). If you are running everything under a small home directory on an HPC, then you might run up against space issues. If this is the case, I would recommend installing your conda environment under a different directory/file system (you can do this with the `--prefix <dir>` flag when creating new environments.
