### ISSUE TITLE
How to use MINTIE with Uncompressed FASTQ Files?

### ISSUE THREAD

**Issue by sumitm89** [Oshlack/MINTIE#36]
The datasets I am working with consists of a large collection of paired-end FASTQ files, which are not in the .gz compressed format. When I attempt to run MINTIE with these uncompressed files by modifying the params.txt file (-p fastqCaseFormat=cases/%_R*.fastq;
-p fastqControlFormat=controls/%_R*.fastq). But, I encounter an error message that says, “Stage fastq_dedupe unable to locate one or more inputs specified by 'from' ending with [*.gz]”. 

I understand that MINTIE is currently configured to work with gzipped fastq files. However, given the volume of data I am dealing with, it would be incredibly helpful if I could use MINTIE directly on uncompressed FASTQ files. This would save a significant amount of time that would otherwise be spent on file conversion. If it is possible to modify MINTIE to enable the direct use of FASTQ files, I would greatly appreciate your guidance on how to make this happen.

**Comment by mcmero** [comment]
Unfortunately, the pipeline is hard-coded for gzipped fastq files in quite a few places, making it tricky to modify the pipeline to handle unzipped fastq files. The easiest solution would be to gzip the files. You may want to look into using something like `pigz`, which is a multi-threaded version of gzip to speed things up.
