### ISSUE TITLE
Pipeline fail at "annotate contigs"

### ISSUE THREAD

**Issue by stephenrdoyle** [Oshlack/MINTIE#4]
Hi, 

Congratulations on the recent bioRxiv - I really enjoyed it and (hopefully) look forward to applying it in my work.

I am currently trying to test it out on my non-human non-model organism, and I am getting an error that I am struggling to troubleshoot at the "annotate contigs" stage. The error is below. Is there something obvious I should look at that I am missing?

Any advice is greatly appreciated.
Kind regards, 
Steve

================================= Stage annotate_contigs (7554789) =================================
Traceback (most recent call last):
  File "/nfs/users/nfs_s/sd21/lustre118_link/software/TRANSCRIPTOME/MINTIE/annotate/annotate_contigs.py", line 28, in <module>
    from utils import cached, init_logging, exit_with_error
  File "/lustre/scratch118/infgen/team133/sd21/software/TRANSCRIPTOME/MINTIE/annotate/utils.py", line 17
    print("{} ERROR: {}, exiting".format(PROGRAM_NAME, message), file=sys.stderr)
                                                                     ^
SyntaxError: invalid syntax

**Comment by mcmero** [comment]
Hi Stephen,

Thanks, I appreciate your thoughts on the paper. 

Regarding your error report, which version of python are you using? The given line will cause a syntax error in python 2.7, so please try python 3, ideally 3.7+. Also, make sure the right version of python is being called in the `tools.groovy` file, found in MINTIE's root directory.

Cheers,
Marek
