### ISSUE TITLE
URL for Hisat2 broken in install_linux64.sh

### ISSUE THREAD

**Issue by nadiadavidson** [Oshlack/MINTIE#9]
The following line fails:
wget --no-check-certificate http://ccb.jhu.edu/software/hisat2/dl/hisat2-2.1.0-Linux_x86_64.zip
Could replace with:
wget "https://cloud.biohpc.swmed.edu/index.php/s/hisat2-210-Linux_x86_64/download" -O hisat2-2.1.0-Linux_x86_64.zip

**Comment by leipzig** [comment]
this tool looks great but it desperately needs a bioconda package. this installer is nuts.

**Comment by mcmero** [comment]
HiSat2 is no longer required for MINTIE and has been removed from the installer. 

The large number of dependencies makes automated installation tricky, but we are looking into ways to streamline the process.
